### ISSUE TITLE
Large molecules not supported

### ISSUE THREAD

**Issue by hackdev17** [hackdev17/smi2latex#1]
Large and Complex molecules may not be give correct output i.e Estrogen, Glucose etc

Also some times benzene compounds not work and aromatic circles option doesn't even effect it

**Comment by hackdev17** [comment]
I will suggest to use jchempaint and draw benzene or other molecules then save it in a folder as *.mol and run directly mol2chemfig. But the rings around benzene is not supported yet.

**Comment by Augus1999** [comment]
Hi, I think only "isomeric SMILES" can give you a structure containing clear stereochemistry. And to render the aromatic "ring" additional package (mol2chemfig) should be installed and called in latex.
For example:
```latex
\documentclass[a4paper]{article}
\usepackage{chemfig}
\usepackage{mol2chemfig}

\begin{document}
	% mol2chemfig -zw -i pubchem 5793
	\chemfig{H-[:90,0.62](<:[:210]O-[:150,0.62]H)-[:330](<[:270]O-[:330,0.62]H)%
		(-[:210,0.62]H)-[:30](<:[:330]O-[:30,0.62]H)(-[:270,0.62]H)-[:90](-[:30]O%
		-[:90,0.62]H)(-[:90,0.62]H)-[:150]O-[:210](-[:270])(-[:90,0.62]H)<[:150](%
		-[:170,0.62]H)(-[:250,0.62]H)-[:90]O-[:150,0.62]H}
	
	% mol2chemfig -zw -i direct "C([C@@H]1[C@H]([C@@H]([C@H](C(O1)O)O)O)O)O"
	\chemfig{OH-[:120,,1]-[:180](<:[:240,,,2]HO)-[:120](<[:180,,,2]HO)-[:60](%
		<:[:120,,,2]HO)-(-[:300]O-[:240])<[:60]-[,,,1]OH}
	
	% mol2chemfig -zwo -i pubchem 996
	\chemfig{H-[:330,0.62]-[:30](-[:90]O-[:30,0.62]H)(%
		-[:270,,,,draw=none]\mcfcringle{1.3})-[:330](-[:30,0.62]H)-[:270](%
		-[:330,0.62]H)-[:210](-[:270,0.62]H)-[:150](-[:90])-[:210,0.62]H}
\end{document}
```
which gives
![chemfig_test-1](https://user-images.githubusercontent.com/39725660/180620120-18f23473-505e-4946-814d-f8edb66d0f8d.png)

**Comment by hackdev17** [comment]
Isomeric Smiles, that's easily generated in jchempaint applications
The fact that mol2chemfig has -i direct <smiles> I didn't get know 🤦‍♂️
Thanks for guidance add this info to readme.

**Comment by hackdev17** [comment]
Both Shell script and readme are Updated !
